Migrate file manager to compose navigation
flipperdevices/Flipper-Android-App pull request #299
Opened 2022-07-29 17:11 UTC by LionZXY

**Background**

Now we use fragments and cicerone in file manager

**Changes**

- Use jetpack compose navigation

**Test plan**

Try navigate inside filemanager

2022-07-29 17:36 UTC, Programistich requested changes

2022-07-29 17:36 UTC, Programistich commented on components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt
> +        navController.navigate(NavGraphRoute.ScreenStreaming.name)
You dont remember pop to here?

2022-07-30 09:41 UTC, LionZXY commented on components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt
> +        navController.navigate(NavGraphRoute.ScreenStreaming.name)
What's it for? Everything works without it.

2022-07-30 13:51 UTC, Programistich approved these changes

2022-07-30 21:15 UTC, merged