Migrate to new device info api
flipperdevices/Flipper-Android-App pull request #526
Opened 2023-02-17 14:31 UTC by LionZXY

**Background**

Please, describe here why you create this PR

**Changes**

- Move rpc information from bridge module
- Not execute rpc information on each connection
- Support old and new api for rpc information
- Not execute rpc information if not open full info

**Test plan**

Try open full info and device info

2023-02-17 18:27 UTC, Programistich commented on components/analytics/shake2report/impl/build.gradle.kts
> +
necessary line

2023-02-17 18:50 UTC, Programistich requested changes

2023-02-17 18:50 UTC, Programistich commented on components/bridge/rpcinfo/api/src/main/java/com/flipperdevices/bridge/rpcinfo/model/FlipperStorageInformation.kt
> +fun <T> FlipperInformationStatus<T>.dataOrNull() = when (this) {
How about set this method inside FlipperInformationStatus?

2023-02-19 16:32 UTC, LionZXY commented on components/bridge/rpcinfo/api/src/main/java/com/flipperdevices/bridge/rpcinfo/model/FlipperStorageInformation.kt
> +fun <T> FlipperInformationStatus<T>.dataOrNull() = when (this) {
It was important for me to separate the data from the data processing methods

2023-02-21 08:49 UTC, merged