Google Assistant v2
flipperdevices/Flipper-Android-App pull request #617
Opened 2023-06-14 20:08 UTC by Programistich

**Background**

Google Assistant like open ping OR find in Flipper App

**Changes**

* Use url template for open application

**Test plan**

* Publish on Google Play and try say "Ok Google, open ping in Flipper App"

2023-06-15 07:08 UTC, LionZXY submitted a review, later dismissed

2023-06-15 15:17 UTC, LionZXY requested changes

2023-06-15 15:17 UTC, LionZXY commented on build-logic/plugins/convention/src/main/kotlin/com/flipperdevices/buildlogic/ApkConfig.kt
> +    const val APPLICATION_ID = "com.test.flipperdevices"
Could you, please, revert debug changes?

2023-07-04 08:34 UTC, Programistich reviewed
Test review for github app

2023-09-02 11:24 UTC, closed without merging